name: HawkScan Example

on:
  workflow_dispatch:

jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Required for actions/checkout to fetch the code
      security-events: write  # Required for uploading SARIF results to GitHub Code Scanning

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Optional: If you need to build and run the JavaSpringVulny app, you can use the below block
      # - name: Download and run JavaSpringVulny release jar
      #   run: |
      #     curl -Ls https://github.com/kaakaww/javaspringvulny/releases/download/0.2.0/java-spring-vuly-0.2.0.jar -o ./java-spring-vuly-0.2.0.jar
      #     java -jar ./java-spring-vuly-0.2.0.jar &

      - name: Build and run JavaSpringVulny (slower)
        run: |
          ./gradlew build
          ./gradlew bootRun &

      - name: Run HawkScan
        id: run-hawkscan
        uses: stackhawk/hawkscan-action@main
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
        env:
          APP_ID: ${{ secrets.appId }}
          NO_PROGRESS: true
          SARIF_ARTIFACT: true

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: stackhawk.sarif  # Path to SARIF file relative to the root of the repository
          category: StackHawk  # Optional category for the results
